export const wordBank = [
  // Fruits
  { word: "Apple", category: "Fruits", difficulty: 1 },
  { word: "Banana", category: "Fruits", difficulty: 1 },
  { word: "Cherry", category: "Fruits", difficulty: 1 },
  { word: "Date", category: "Fruits", difficulty: 1 },
  { word: "Elderberry", category: "Fruits", difficulty: 1 },
  { word: "Fig", category: "Fruits", difficulty: 1 },
  { word: "Grape", category: "Fruits", difficulty: 1 },
  { word: "Honeydew", category: "Fruits", difficulty: 1 },
  { word: "Kiwi", category: "Fruits", difficulty: 1 },
  { word: "Lemon", category: "Fruits", difficulty: 1 },
  { word: "Mango", category: "Fruits", difficulty: 1 },
  { word: "Nectarine", category: "Fruits", difficulty: 1 },
  { word: "Orange", category: "Fruits", difficulty: 1 },
  { word: "Papaya", category: "Fruits", difficulty: 1 },
  { word: "Quince", category: "Fruits", difficulty: 1 },
  { word: "Raspberry", category: "Fruits", difficulty: 1 },
  { word: "Strawberry", category: "Fruits", difficulty: 1 },
  { word: "Tangerine", category: "Fruits", difficulty: 1 },
  { word: "Ugli fruit", category: "Fruits", difficulty: 1 },
  { word: "Watermelon", category: "Fruits", difficulty: 1 },
  { word: "Blackberry", category: "Fruits", difficulty: 1 },
  { word: "Blueberry", category: "Fruits", difficulty: 1 },
  { word: "Cantaloupe", category: "Fruits", difficulty: 1 },
  { word: "Coconut", category: "Fruits", difficulty: 1 },
  { word: "Cranberry", category: "Fruits", difficulty: 1 },
  { word: "Gooseberry", category: "Fruits", difficulty: 1 },
  { word: "Guava", category: "Fruits", difficulty: 1 },
  { word: "Jackfruit", category: "Fruits", difficulty: 1 },
  { word: "Jujube", category: "Fruits", difficulty: 1 },
  { word: "Kumquat", category: "Fruits", difficulty: 1 },
  { word: "Lychee", category: "Fruits", difficulty: 1 },
  { word: "Mulberry", category: "Fruits", difficulty: 1 },
  { word: "Olive", category: "Fruits", difficulty: 1 },
  { word: "Peach", category: "Fruits", difficulty: 1 },
  { word: "Pear", category: "Fruits", difficulty: 1 },
  { word: "Persimmon", category: "Fruits", difficulty: 1 },
  { word: "Pineapple", category: "Fruits", difficulty: 1 },
  { word: "Plum", category: "Fruits", difficulty: 1 },
  { word: "Pomegranate", category: "Fruits", difficulty: 1 },
  { word: "Starfruit", category: "Fruits", difficulty: 1 },
  { word: "Cactus pear", category: "Fruits", difficulty: 1 },
  { word: "Durian", category: "Fruits", difficulty: 1 },
  { word: "Tamarind", category: "Fruits", difficulty: 1 },
  { word: "Sapodilla", category: "Fruits", difficulty: 1 },
  { word: "Mangosteen", category: "Fruits", difficulty: 1 },
  { word: "Longan", category: "Fruits", difficulty: 1 },
  { word: "Feijoa", category: "Fruits", difficulty: 1 },
  { word: "Salak", category: "Fruits", difficulty: 1 },
  { word: "Maracuja", category: "Fruits", difficulty: 1 },
  { word: "Miracle fruit", category: "Fruits", difficulty: 1 },
  { word: "Ackee", category: "Fruits", difficulty: 1 },
  { word: "Bilberry", category: "Fruits", difficulty: 1 },
  { word: "Boysenberry", category: "Fruits", difficulty: 1 },
  { word: "Cloudberry", category: "Fruits", difficulty: 1 },
  { word: "Currant", category: "Fruits", difficulty: 1 },
  { word: "Dragonfruit", category: "Fruits", difficulty: 1 },
  { word: "Elderberry", category: "Fruits", difficulty: 1 },
  { word: "Horned melon", category: "Fruits", difficulty: 1 },
  { word: "Medlar", category: "Fruits", difficulty: 1 },
  { word: "Noni", category: "Fruits", difficulty: 1 },
  { word: "Rambutan", category: "Fruits", difficulty: 1 },
  { word: "Santol", category: "Fruits", difficulty: 1 },
  { word: "Yumberry", category: "Fruits", difficulty: 1 },

  // Animals
  { word: "Tiger", category: "Animals", difficulty: 1 },
  { word: "Bear", category: "Animals", difficulty: 1 },
  { word: "Zebra", category: "Animals", difficulty: 1 },
  { word: "Lion", category: "Animals", difficulty: 1 },
  { word: "Elephant", category: "Animals", difficulty: 1 },
  { word: "Giraffe", category: "Animals", difficulty: 1 },
  { word: "Wolf", category: "Animals", difficulty: 1 },
  { word: "Rabbit", category: "Animals", difficulty: 1 },
  { word: "Kangaroo", category: "Animals", difficulty: 1 },
  { word: "Panda", category: "Animals", difficulty: 1 },
  { word: "Cheetah", category: "Animals", difficulty: 1 },
  { word: "Hippo", category: "Animals", difficulty: 1 },
  { word: "Rhino", category: "Animals", difficulty: 1 },
  { word: "Koala", category: "Animals", difficulty: 1 },
  { word: "Monkey", category: "Animals", difficulty: 1 },
  { word: "Chimpanzee", category: "Animals", difficulty: 1 },
  { word: "Gorilla", category: "Animals", difficulty: 1 },
  { word: "Orangutan", category: "Animals", difficulty: 1 },
  { word: "Sloth", category: "Animals", difficulty: 1 },
  { word: "Otter", category: "Animals", difficulty: 1 },
  { word: "Fox", category: "Animals", difficulty: 1 },
  { word: "Raccoon", category: "Animals", difficulty: 1 },
  { word: "Squirrel", category: "Animals", difficulty: 1 },
  { word: "Deer", category: "Animals", difficulty: 1 },
  { word: "Moose", category: "Animals", difficulty: 1 },
  { word: "Buffalo", category: "Animals", difficulty: 1 },
  { word: "Horse", category: "Animals", difficulty: 1 },
  { word: "Cow", category: "Animals", difficulty: 1 },
  { word: "Pig", category: "Animals", difficulty: 1 },
  { word: "Sheep", category: "Animals", difficulty: 1 },
  { word: "Goat", category: "Animals", difficulty: 1 },
  { word: "Camel", category: "Animals", difficulty: 1 },
  { word: "Donkey", category: "Animals", difficulty: 1 },
  { word: "Chicken", category: "Animals", difficulty: 1 },
  { word: "Duck", category: "Animals", difficulty: 1 },
  { word: "Goose", category: "Animals", difficulty: 1 },
  { word: "Turkey", category: "Animals", difficulty: 1 },
  { word: "Peacock", category: "Animals", difficulty: 1 },
  { word: "Ostrich", category: "Animals", difficulty: 1 },
  { word: "Penguin", category: "Animals", difficulty: 1 },
  { word: "Eagle", category: "Animals", difficulty: 1 },
  { word: "Hawk", category: "Animals", difficulty: 1 },
  { word: "Owl", category: "Animals", difficulty: 1 },
  { word: "Falcon", category: "Animals", difficulty: 1 },
  { word: "Parrot", category: "Animals", difficulty: 1 },
  { word: "Swan", category: "Animals", difficulty: 1 },
  { word: "Flamingo", category: "Animals", difficulty: 1 },
  { word: "Crane", category: "Animals", difficulty: 1 },
  { word: "Heron", category: "Animals", difficulty: 1 },
  { word: "Dolphin", category: "Animals", difficulty: 1 },
  { word: "Whale", category: "Animals", difficulty: 1 },
  { word: "Shark", category: "Animals", difficulty: 1 },
  { word: "Octopus", category: "Animals", difficulty: 1 },
  { word: "Squid", category: "Animals", difficulty: 1 },
  { word: "Seal", category: "Animals", difficulty: 1 },
  { word: "Walrus", category: "Animals", difficulty: 1 },
  { word: "Crab", category: "Animals", difficulty: 1 },
  { word: "Lobster", category: "Animals", difficulty: 1 },
  { word: "Jellyfish", category: "Animals", difficulty: 1 },
  { word: "Starfish", category: "Animals", difficulty: 1 },
  { word: "Frog", category: "Animals", difficulty: 1 },
  { word: "Toad", category: "Animals", difficulty: 1 },
  { word: "Snake", category: "Animals", difficulty: 1 },
  { word: "Crocodile", category: "Animals", difficulty: 1 },
  { word: "Alligator", category: "Animals", difficulty: 1 },
  { word: "Lizard", category: "Animals", difficulty: 1 },
  { word: "Turtle", category: "Animals", difficulty: 1 },

  // Colors
  { word: "Red", category: "Colors", difficulty: 1 },
  { word: "Blue", category: "Colors", difficulty: 1 },
  { word: "Green", category: "Colors", difficulty: 1 },
  { word: "Yellow", category: "Colors", difficulty: 1 },
  { word: "Purple", category: "Colors", difficulty: 1 },
  { word: "Orange", category: "Colors", difficulty: 1 },
  { word: "Pink", category: "Colors", difficulty: 1 },
  { word: "Brown", category: "Colors", difficulty: 1 },
  { word: "Black", category: "Colors", difficulty: 1 },
  { word: "White", category: "Colors", difficulty: 1 },
  { word: "Gray", category: "Colors", difficulty: 1 },
  { word: "Cyan", category: "Colors", difficulty: 1 },
  { word: "Magenta", category: "Colors", difficulty: 1 },
  { word: "Teal", category: "Colors", difficulty: 1 },
  { word: "Turquoise", category: "Colors", difficulty: 1 },
  { word: "Beige", category: "Colors", difficulty: 1 },
  { word: "Lavender", category: "Colors", difficulty: 1 },
  { word: "Maroon", category: "Colors", difficulty: 1 },
  { word: "Olive", category: "Colors", difficulty: 1 },
  { word: "Navy", category: "Colors", difficulty: 1 },
  { word: "Burgundy", category: "Colors", difficulty: 1 },
  { word: "Periwinkle", category: "Colors", difficulty: 1 },
  { word: "Violet", category: "Colors", difficulty: 1 },
  { word: "Peach", category: "Colors", difficulty: 1 },
  { word: "Salmon", category: "Colors", difficulty: 1 },
  { word: "Coral", category: "Colors", difficulty: 1 },
  { word: "Indigo", category: "Colors", difficulty: 1 },
  { word: "Amber", category: "Colors", difficulty: 1 },
  { word: "Chartreuse", category: "Colors", difficulty: 1 },
  { word: "Crimson", category: "Colors", difficulty: 1 },
  { word: "Ivory", category: "Colors", difficulty: 1 },
  { word: "Khaki", category: "Colors", difficulty: 1 },
  { word: "Bronze", category: "Colors", difficulty: 1 },
  { word: "Silver", category: "Colors", difficulty: 1 },
  { word: "Gold", category: "Colors", difficulty: 1 },
  { word: "Rose", category: "Colors", difficulty: 1 },
  { word: "Ruby", category: "Colors", difficulty: 1 },
  { word: "Emerald", category: "Colors", difficulty: 1 },
  { word: "Sapphire", category: "Colors", difficulty: 1 },
  { word: "Amethyst", category: "Colors", difficulty: 1 },
  { word: "Opal", category: "Colors", difficulty: 1 },
  { word: "Topaz", category: "Colors", difficulty: 1 },
  { word: "Pearl", category: "Colors", difficulty: 1 },
  { word: "Lilac", category: "Colors", difficulty: 1 },
  { word: "Mint", category: "Colors", difficulty: 1 },
  { word: "Mauve", category: "Colors", difficulty: 1 },
  { word: "Taupe", category: "Colors", difficulty: 1 },

  // Planets
  { word: "Mercury", category: "Planets", difficulty: 2 },
  { word: "Venus", category: "Planets", difficulty: 2 },
  { word: "Earth", category: "Planets", difficulty: 2 },
  { word: "Mars", category: "Planets", difficulty: 2 },
  { word: "Jupiter", category: "Planets", difficulty: 2 },
  { word: "Saturn", category: "Planets", difficulty: 2 },
  { word: "Uranus", category: "Planets", difficulty: 2 },
  { word: "Neptune", category: "Planets", difficulty: 2 },
  { word: "Pluto", category: "Planets", difficulty: 2 },
  { word: "Ceres", category: "Planets", difficulty: 2 },
  { word: "Eris", category: "Planets", difficulty: 2 },
  { word: "Haumea", category: "Planets", difficulty: 2 },
  { word: "Makemake", category: "Planets", difficulty: 2 },
  { word: "Ganymede", category: "Planets", difficulty: 2 },
  { word: "Titan", category: "Planets", difficulty: 2 },
  { word: "Callisto", category: "Planets", difficulty: 2 },
  { word: "Io", category: "Planets", difficulty: 2 },
  { word: "Europa", category: "Planets", difficulty: 2 },
  { word: "Triton", category: "Planets", difficulty: 2 },
  { word: "Enceladus", category: "Planets", difficulty: 2 },
  { word: "Rhea", category: "Planets", difficulty: 2 },
  { word: "Iapetus", category: "Planets", difficulty: 2 },
  { word: "Oberon", category: "Planets", difficulty: 2 },
  { word: "Titania", category: "Planets", difficulty: 2 },
  { word: "Miranda", category: "Planets", difficulty: 2 },
  { word: "Ariel", category: "Planets", difficulty: 2 },
  { word: "Umbriel", category: "Planets", difficulty: 2 },
  { word: "Charon", category: "Planets", difficulty: 2 },
  { word: "Phobos", category: "Planets", difficulty: 2 },
  { word: "Deimos", category: "Planets", difficulty: 2 },
  { word: "Vesta", category: "Planets", difficulty: 2 },
  { word: "Pallas", category: "Planets", difficulty: 2 },
  { word: "Hygiea", category: "Planets", difficulty: 2 },
  { word: "Sedna", category: "Planets", difficulty: 2 },
  { word: "Quaoar", category: "Planets", difficulty: 2 },
  { word: "Orcus", category: "Planets", difficulty: 2 },
  { word: "Salacia", category: "Planets", difficulty: 2 },
  { word: "Varuna", category: "Planets", difficulty: 2 },
  { word: "Ixion", category: "Planets", difficulty: 2 },
  { word: "Huya", category: "Planets", difficulty: 2 },
  { word: "Gonggong", category: "Planets", difficulty: 2 },
  { word: "Albion", category: "Planets", difficulty: 2 },
  { word: "Chaos", category: "Planets", difficulty: 2 },
  { word: "Zhongguo", category: "Planets", difficulty: 2 },
  { word: "Tyche", category: "Planets", difficulty: 2 },
  { word: "Nemesis", category: "Planets", difficulty: 2 },

  // Sports
  { word: "Soccer", category: "Sports", difficulty: 2 },
  { word: "Basketball", category: "Sports", difficulty: 2 },
  { word: "Baseball", category: "Sports", difficulty: 2 },
  { word: "Tennis", category: "Sports", difficulty: 2 },
  { word: "Golf", category: "Sports", difficulty: 2 },
  { word: "Hockey", category: "Sports", difficulty: 2 },
  { word: "Football", category: "Sports", difficulty: 2 },
  { word: "Rugby", category: "Sports", difficulty: 2 },
  { word: "Cricket", category: "Sports", difficulty: 2 },
  { word: "Volleyball", category: "Sports", difficulty: 2 },
  { word: "Badminton", category: "Sports", difficulty: 2 },
  { word: "Table Tennis", category: "Sports", difficulty: 2 },
  { word: "Wrestling", category: "Sports", difficulty: 2 },
  { word: "Boxing", category: "Sports", difficulty: 2 },
  { word: "MMA", category: "Sports", difficulty: 2 },
  { word: "Swimming", category: "Sports", difficulty: 2 },
  { word: "Diving", category: "Sports", difficulty: 2 },
  { word: "Gymnastics", category: "Sports", difficulty: 2 },
  { word: "Track and Field", category: "Sports", difficulty: 2 },
  { word: "Marathon", category: "Sports", difficulty: 2 },
  { word: "Cycling", category: "Sports", difficulty: 2 },
  { word: "Rowing", category: "Sports", difficulty: 2 },
  { word: "Sailing", category: "Sports", difficulty: 2 },
  { word: "Archery", category: "Sports", difficulty: 2 },
  { word: "Shooting", category: "Sports", difficulty: 2 },
  { word: "Fencing", category: "Sports", difficulty: 2 },
  { word: "Judo", category: "Sports", difficulty: 2 },
  { word: "Karate", category: "Sports", difficulty: 2 },
  { word: "Taekwondo", category: "Sports", difficulty: 2 },
  { word: "Skiing", category: "Sports", difficulty: 2 },
  { word: "Snowboarding", category: "Sports", difficulty: 2 },
  { word: "Ice Skating", category: "Sports", difficulty: 2 },
  { word: "Bobsleigh", category: "Sports", difficulty: 2 },
  { word: "Luge", category: "Sports", difficulty: 2 },
  { word: "Curling", category: "Sports", difficulty: 2 },
  { word: "Surfing", category: "Sports", difficulty: 2 },
  { word: "Skateboarding", category: "Sports", difficulty: 2 },
  { word: "Rock Climbing", category: "Sports", difficulty: 2 },
  { word: "Equestrian", category: "Sports", difficulty: 2 },
  { word: "Handball", category: "Sports", difficulty: 2 },
  { word: "Water Polo", category: "Sports", difficulty: 2 },
  { word: "Lacrosse", category: "Sports", difficulty: 2 },
  { word: "Field Hockey", category: "Sports", difficulty: 2 },
  { word: "Polo", category: "Sports", difficulty: 2 },
  { word: "Triathlon", category: "Sports", difficulty: 2 },
  { word: "Motorsport", category: "Sports", difficulty: 2 },
  { word: "Snooker", category: "Sports", difficulty: 2 },
  { word: "Darts", category: "Sports", difficulty: 2 },

  // Instruments
  { word: "Guitar", category: "Instruments", difficulty: 2 },
  { word: "Piano", category: "Instruments", difficulty: 2 },
  { word: "Violin", category: "Instruments", difficulty: 2 },
  { word: "Drums", category: "Instruments", difficulty: 2 },
  { word: "Flute", category: "Instruments", difficulty: 2 },
  { word: "Trumpet", category: "Instruments", difficulty: 2 },
  { word: "Saxophone", category: "Instruments", difficulty: 2 },
  { word: "Clarinet", category: "Instruments", difficulty: 2 },
  { word: "Trombone", category: "Instruments", difficulty: 2 },
  { word: "Cello", category: "Instruments", difficulty: 2 },
  { word: "Double Bass", category: "Instruments", difficulty: 2 },
  { word: "Oboe", category: "Instruments", difficulty: 2 },
  { word: "Bassoon", category: "Instruments", difficulty: 2 },
  { word: "Harp", category: "Instruments", difficulty: 2 },
  { word: "Ukulele", category: "Instruments", difficulty: 2 },
  { word: "Banjo", category: "Instruments", difficulty: 2 },
  { word: "Mandolin", category: "Instruments", difficulty: 2 },
  { word: "Accordion", category: "Instruments", difficulty: 2 },
  { word: "Harmonica", category: "Instruments", difficulty: 2 },
  { word: "Xylophone", category: "Instruments", difficulty: 2 },
  { word: "Marimba", category: "Instruments", difficulty: 2 },
  { word: "Vibraphone", category: "Instruments", difficulty: 2 },
  { word: "Timpani", category: "Instruments", difficulty: 2 },
  { word: "Snare Drum", category: "Instruments", difficulty: 2 },
  { word: "Bass Drum", category: "Instruments", difficulty: 2 },
  { word: "Cymbals", category: "Instruments", difficulty: 2 },
  { word: "Glockenspiel", category: "Instruments", difficulty: 2 },
  { word: "Bagpipes", category: "Instruments", difficulty: 2 },
  { word: "Recorder", category: "Instruments", difficulty: 2 },
  { word: "Synthesizer", category: "Instruments", difficulty: 2 },
  { word: "Electric Guitar", category: "Instruments", difficulty: 2 },
  { word: "Bass Guitar", category: "Instruments", difficulty: 2 },
  { word: "Keytar", category: "Instruments", difficulty: 2 },
  { word: "Melodica", category: "Instruments", difficulty: 2 },
  { word: "Bongos", category: "Instruments", difficulty: 2 },
  { word: "Conga", category: "Instruments", difficulty: 2 },
  { word: "Djembe", category: "Instruments", difficulty: 2 },
  { word: "Steel Drum", category: "Instruments", difficulty: 2 },
  { word: "Pan Flute", category: "Instruments", difficulty: 2 },
  { word: "Zither", category: "Instruments", difficulty: 2 },
  { word: "Ocarina", category: "Instruments", difficulty: 2 },
  { word: "Kazoo", category: "Instruments", difficulty: 2 },
  { word: "Theremin", category: "Instruments", difficulty: 2 },
  { word: "Glass Harmonica", category: "Instruments", difficulty: 2 },
  { word: "Didgeridoo", category: "Instruments", difficulty: 2 },
  { word: "Tabla", category: "Instruments", difficulty: 2 },
  { word: "Sitar", category: "Instruments", difficulty: 2 },
  { word: "Shamisen", category: "Instruments", difficulty: 2 },

  // Vehicles
  { word: "Car", category: "Vehicles", difficulty: 2 },
  { word: "Bicycle", category: "Vehicles", difficulty: 2 },
  { word: "Motorcycle", category: "Vehicles", difficulty: 2 },
  { word: "Truck", category: "Vehicles", difficulty: 2 },
  { word: "Bus", category: "Vehicles", difficulty: 2 },
  { word: "Van", category: "Vehicles", difficulty: 2 },
  { word: "Train", category: "Vehicles", difficulty: 2 },
  { word: "Subway", category: "Vehicles", difficulty: 2 },
  { word: "Tram", category: "Vehicles", difficulty: 2 },
  { word: "Trolleybus", category: "Vehicles", difficulty: 2 },
  { word: "Airplane", category: "Vehicles", difficulty: 2 },
  { word: "Helicopter", category: "Vehicles", difficulty: 2 },
  { word: "Jet", category: "Vehicles", difficulty: 2 },
  { word: "Glider", category: "Vehicles", difficulty: 2 },
  { word: "Hot Air Balloon", category: "Vehicles", difficulty: 2 },
  { word: "Blimp", category: "Vehicles", difficulty: 2 },
  { word: "Boat", category: "Vehicles", difficulty: 2 },
  { word: "Ship", category: "Vehicles", difficulty: 2 },
  { word: "Yacht", category: "Vehicles", difficulty: 2 },
  { word: "Sailboat", category: "Vehicles", difficulty: 2 },
  { word: "Canoe", category: "Vehicles", difficulty: 2 },
  { word: "Kayak", category: "Vehicles", difficulty: 2 },
  { word: "Rowboat", category: "Vehicles", difficulty: 2 },
  { word: "Ferry", category: "Vehicles", difficulty: 2 },
  { word: "Hovercraft", category: "Vehicles", difficulty: 2 },
  { word: "Submarine", category: "Vehicles", difficulty: 2 },
  { word: "Spaceship", category: "Vehicles", difficulty: 2 },
  { word: "Rocket", category: "Vehicles", difficulty: 2 },
  { word: "Scooter", category: "Vehicles", difficulty: 2 },
  { word: "Moped", category: "Vehicles", difficulty: 2 },
  { word: "Skateboard", category: "Vehicles", difficulty: 2 },
  { word: "Golf Cart", category: "Vehicles", difficulty: 2 },
  { word: "Snowmobile", category: "Vehicles", difficulty: 2 },
  { word: "Tank", category: "Vehicles", difficulty: 2 },
  { word: "Bulldozer", category: "Vehicles", difficulty: 2 },
  { word: "Tractor", category: "Vehicles", difficulty: 2 },
  { word: "ATV", category: "Vehicles", difficulty: 2 },
  { word: "Campervan", category: "Vehicles", difficulty: 2 },
  { word: "Caravan", category: "Vehicles", difficulty: 2 },
  { word: "Limo", category: "Vehicles", difficulty: 2 },
  { word: "Pickup Truck", category: "Vehicles", difficulty: 2 },
  { word: "Fire Truck", category: "Vehicles", difficulty: 2 },
  { word: "Ambulance", category: "Vehicles", difficulty: 2 },
  { word: "Police Car", category: "Vehicles", difficulty: 2 },
  { word: "Garbage Truck", category: "Vehicles", difficulty: 2 },
  { word: "Forklift", category: "Vehicles", difficulty: 2 },
  { word: "Cement Mixer", category: "Vehicles", difficulty: 2 },

  // Automobile Companies
  { word: "Toyota", category: "Automobile Companies", difficulty: 3 },
  { word: "Honda", category: "Automobile Companies", difficulty: 3 },
  { word: "Ford", category: "Automobile Companies", difficulty: 3 },
  { word: "Chevrolet", category: "Automobile Companies", difficulty: 3 },
  { word: "Tesla", category: "Automobile Companies", difficulty: 3 },
  { word: "BMW", category: "Automobile Companies", difficulty: 3 },
  { word: "Mercedes-Benz", category: "Automobile Companies", difficulty: 3 },
  { word: "Audi", category: "Automobile Companies", difficulty: 3 },
  { word: "Volkswagen", category: "Automobile Companies", difficulty: 3 },
  { word: "Porsche", category: "Automobile Companies", difficulty: 3 },
  { word: "Lexus", category: "Automobile Companies", difficulty: 3 },
  { word: "Subaru", category: "Automobile Companies", difficulty: 3 },
  { word: "Mazda", category: "Automobile Companies", difficulty: 3 },
  { word: "Hyundai", category: "Automobile Companies", difficulty: 3 },
  { word: "Kia", category: "Automobile Companies", difficulty: 3 },
  { word: "Nissan", category: "Automobile Companies", difficulty: 3 },
  { word: "Infiniti", category: "Automobile Companies", difficulty: 3 },
  { word: "Acura", category: "Automobile Companies", difficulty: 3 },
  { word: "Mitsubishi", category: "Automobile Companies", difficulty: 3 },
  { word: "Jeep", category: "Automobile Companies", difficulty: 3 },
  { word: "Chrysler", category: "Automobile Companies", difficulty: 3 },
  { word: "Dodge", category: "Automobile Companies", difficulty: 3 },
  { word: "Ram", category: "Automobile Companies", difficulty: 3 },
  { word: "Buick", category: "Automobile Companies", difficulty: 3 },
  { word: "GMC", category: "Automobile Companies", difficulty: 3 },
  { word: "Cadillac", category: "Automobile Companies", difficulty: 3 },
  { word: "Lincoln", category: "Automobile Companies", difficulty: 3 },
  { word: "Fiat", category: "Automobile Companies", difficulty: 3 },
  { word: "Alfa Romeo", category: "Automobile Companies", difficulty: 3 },
  { word: "Maserati", category: "Automobile Companies", difficulty: 3 },
  { word: "Ferrari", category: "Automobile Companies", difficulty: 3 },
  { word: "Lamborghini", category: "Automobile Companies", difficulty: 3 },
  { word: "Bentley", category: "Automobile Companies", difficulty: 3 },
  { word: "Rolls-Royce", category: "Automobile Companies", difficulty: 3 },
  { word: "McLaren", category: "Automobile Companies", difficulty: 3 },
  { word: "Aston Martin", category: "Automobile Companies", difficulty: 3 },
  { word: "Lotus", category: "Automobile Companies", difficulty: 3 },
  { word: "Bugatti", category: "Automobile Companies", difficulty: 3 },

  // Motorcycle Companies
  { word: "Harley-Davidson", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Honda", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Yamaha", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Kawasaki", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Suzuki", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Ducati", category: "Motorcycle Companies", difficulty: 3 },
  { word: "BMW Motorrad", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Triumph", category: "Motorcycle Companies", difficulty: 3 },
  { word: "KTM", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Aprilia", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Moto Guzzi", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Indian Motorcycle", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Royal Enfield", category: "Motorcycle Companies", difficulty: 3 },
  { word: "MV Agusta", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Bajaj", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Hero MotoCorp", category: "Motorcycle Companies", difficulty: 3 },
  { word: "TVS Motor", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Benelli", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Husqvarna", category: "Motorcycle Companies", difficulty: 3 },
  { word: "GasGas", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Cagiva", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Bimota", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Norton", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Arch Motorcycle", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Lightning Motorcycle", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Zero Motorcycles", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Energica", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Vespa", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Piaggio", category: "Motorcycle Companies", difficulty: 3 },
  { word: "SYM", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Kymco", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Lifan", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Zongshen", category: "Motorcycle Companies", difficulty: 3 },
  { word: "CFMoto", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Loncin", category: "Motorcycle Companies", difficulty: 3 },
  { word: "UM Motorcycles", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Surron", category: "Motorcycle Companies", difficulty: 3 },

  // Famous Singers
  { word: "Elvis Presley", category: "Famous Singers", difficulty: 3 },
  { word: "Michael Jackson", category: "Famous Singers", difficulty: 3 },
  { word: "Madonna", category: "Famous Singers", difficulty: 3 },
  { word: "Whitney Houston", category: "Famous Singers", difficulty: 3 },
  { word: "Freddie Mercury", category: "Famous Singers", difficulty: 3 },
  { word: "Aretha Franklin", category: "Famous Singers", difficulty: 3 },
  { word: "Beyoncé", category: "Famous Singers", difficulty: 3 },
  { word: "Adele", category: "Famous Singers", difficulty: 3 },
  { word: "Taylor Swift", category: "Famous Singers", difficulty: 3 },
  { word: "Frank Sinatra", category: "Famous Singers", difficulty: 3 },
  { word: "Billie Eilish", category: "Famous Singers", difficulty: 3 },
  { word: "Lady Gaga", category: "Famous Singers", difficulty: 3 },
  { word: "Ed Sheeran", category: "Famous Singers", difficulty: 3 },
  { word: "Bruno Mars", category: "Famous Singers", difficulty: 3 },
  { word: "Justin Bieber", category: "Famous Singers", difficulty: 3 },
  { word: "Shakira", category: "Famous Singers", difficulty: 3 },
  { word: "Dolly Parton", category: "Famous Singers", difficulty: 3 },
  { word: "Bob Dylan", category: "Famous Singers", difficulty: 3 },
  { word: "John Lennon", category: "Famous Singers", difficulty: 3 },
  { word: "Paul McCartney", category: "Famous Singers", difficulty: 3 },
  { word: "Elton John", category: "Famous Singers", difficulty: 3 },
  { word: "Prince", category: "Famous Singers", difficulty: 3 },
  { word: "David Bowie", category: "Famous Singers", difficulty: 3 },
  { word: "Stevie Wonder", category: "Famous Singers", difficulty: 3 },
  { word: "Janis Joplin", category: "Famous Singers", difficulty: 3 },
  { word: "Tina Turner", category: "Famous Singers", difficulty: 3 },
  { word: "Mariah Carey", category: "Famous Singers", difficulty: 3 },
  { word: "Christina Aguilera", category: "Famous Singers", difficulty: 3 },
  { word: "Ariana Grande", category: "Famous Singers", difficulty: 3 },
  { word: "Eminem", category: "Famous Singers", difficulty: 3 },
  { word: "Drake", category: "Famous Singers", difficulty: 3 },
  { word: "Rihanna", category: "Famous Singers", difficulty: 3 },
  { word: "Harry Styles", category: "Famous Singers", difficulty: 3 },
  { word: "Bobby Brown", category: "Famous Singers", difficulty: 3 },
  { word: "Sam Smith", category: "Famous Singers", difficulty: 3 },
  { word: "Lana Del Rey", category: "Famous Singers", difficulty: 3 },
  { word: "Miley Cyrus", category: "Famous Singers", difficulty: 3 },
  { word: "Selena Gomez", category: "Famous Singers", difficulty: 3 },

  // Elements
  { word: "Hydrogen", category: "Elements", difficulty: 3 },
  { word: "Helium", category: "Elements", difficulty: 3 },
  { word: "Lithium", category: "Elements", difficulty: 3 },
  { word: "Beryllium", category: "Elements", difficulty: 3 },
  { word: "Boron", category: "Elements", difficulty: 3 },
  { word: "Carbon", category: "Elements", difficulty: 3 },
  { word: "Nitrogen", category: "Elements", difficulty: 3 },
  { word: "Oxygen", category: "Elements", difficulty: 3 },
  { word: "Fluorine", category: "Elements", difficulty: 3 },
  { word: "Neon", category: "Elements", difficulty: 3 },
  { word: "Sodium", category: "Elements", difficulty: 3 },
  { word: "Magnesium", category: "Elements", difficulty: 3 },
  { word: "Aluminum", category: "Elements", difficulty: 3 },
  { word: "Silicon", category: "Elements", difficulty: 3 },
  { word: "Phosphorus", category: "Elements", difficulty: 3 },
  { word: "Sulfur", category: "Elements", difficulty: 3 },
  { word: "Chlorine", category: "Elements", difficulty: 3 },
  { word: "Argon", category: "Elements", difficulty: 3 },
  { word: "Potassium", category: "Elements", difficulty: 3 },
  { word: "Calcium", category: "Elements", difficulty: 3 },
  { word: "Scandium", category: "Elements", difficulty: 3 },
  { word: "Titanium", category: "Elements", difficulty: 3 },
  { word: "Vanadium", category: "Elements", difficulty: 3 },
  { word: "Chromium", category: "Elements", difficulty: 3 },
  { word: "Manganese", category: "Elements", difficulty: 3 },
  { word: "Iron", category: "Elements", difficulty: 3 },
  { word: "Cobalt", category: "Elements", difficulty: 3 },
  { word: "Nickel", category: "Elements", difficulty: 3 },
  { word: "Copper", category: "Elements", difficulty: 3 },
  { word: "Zinc", category: "Elements", difficulty: 3 },
  { word: "Gallium", category: "Elements", difficulty: 3 },
  { word: "Germanium", category: "Elements", difficulty: 3 },
  { word: "Arsenic", category: "Elements", difficulty: 3 },
  { word: "Selenium", category: "Elements", difficulty: 3 },
  { word: "Bromine", category: "Elements", difficulty: 3 },
  { word: "Krypton", category: "Elements", difficulty: 3 },
  { word: "Rubidium", category: "Elements", difficulty: 3 },
  { word: "Strontium", category: "Elements", difficulty: 3 },
  { word: "Yttrium", category: "Elements", difficulty: 3 },
  { word: "Zirconium", category: "Elements", difficulty: 3 },
  { word: "Niobium", category: "Elements", difficulty: 3 },
  { word: "Molybdenum", category: "Elements", difficulty: 3 },
  { word: "Technetium", category: "Elements", difficulty: 3 },
  { word: "Ruthenium", category: "Elements", difficulty: 3 },
  { word: "Rhodium", category: "Elements", difficulty: 3 },
  { word: "Palladium", category: "Elements", difficulty: 3 },
  { word: "Silver", category: "Elements", difficulty: 3 },

  // Languages
  { word: "English", category: "Languages", difficulty: 2 },
  { word: "Spanish", category: "Languages", difficulty: 2 },
  { word: "French", category: "Languages", difficulty: 2 },
  { word: "German", category: "Languages", difficulty: 2 },
  { word: "Italian", category: "Languages", difficulty: 2 },
  { word: "Portuguese", category: "Languages", difficulty: 2 },
  { word: "Russian", category: "Languages", difficulty: 2 },
  { word: "Chinese", category: "Languages", difficulty: 2 },
  { word: "Japanese", category: "Languages", difficulty: 2 },
  { word: "Korean", category: "Languages", difficulty: 2 },
  { word: "Hindi", category: "Languages", difficulty: 2 },
  { word: "Arabic", category: "Languages", difficulty: 2 },
  { word: "Turkish", category: "Languages", difficulty: 2 },
  { word: "Dutch", category: "Languages", difficulty: 2 },
  { word: "Greek", category: "Languages", difficulty: 2 },
  { word: "Hebrew", category: "Languages", difficulty: 2 },
  { word: "Swedish", category: "Languages", difficulty: 2 },
  { word: "Norwegian", category: "Languages", difficulty: 2 },
  { word: "Danish", category: "Languages", difficulty: 2 },
  { word: "Finnish", category: "Languages", difficulty: 2 },
  { word: "Polish", category: "Languages", difficulty: 2 },
  { word: "Czech", category: "Languages", difficulty: 2 },
  { word: "Hungarian", category: "Languages", difficulty: 2 },
  { word: "Romanian", category: "Languages", difficulty: 2 },
  { word: "Thai", category: "Languages", difficulty: 2 },
  { word: "Vietnamese", category: "Languages", difficulty: 2 },
  { word: "Malay", category: "Languages", difficulty: 2 },
  { word: "Indonesian", category: "Languages", difficulty: 2 },
  { word: "Tagalog", category: "Languages", difficulty: 2 },
  { word: "Bengali", category: "Languages", difficulty: 2 },
  { word: "Punjabi", category: "Languages", difficulty: 2 },
  { word: "Tamil", category: "Languages", difficulty: 2 },
  { word: "Telugu", category: "Languages", difficulty: 2 },
  { word: "Urdu", category: "Languages", difficulty: 2 },
  { word: "Swahili", category: "Languages", difficulty: 2 },
  { word: "Zulu", category: "Languages", difficulty: 2 },
  { word: "Hausa", category: "Languages", difficulty: 2 },
  { word: "Yoruba", category: "Languages", difficulty: 2 },
  { word: "Igbo", category: "Languages", difficulty: 2 },
  { word: "Amharic", category: "Languages", difficulty: 2 },
  { word: "Burmese", category: "Languages", difficulty: 2 },
  { word: "Khmer", category: "Languages", difficulty: 2 },
  { word: "Lao", category: "Languages", difficulty: 2 },
  { word: "Mongolian", category: "Languages", difficulty: 2 },
  { word: "Georgian", category: "Languages", difficulty: 2 },
  { word: "Armenian", category: "Languages", difficulty: 2 },
  { word: "Pashto", category: "Languages", difficulty: 2 },
  { word: "Kurdish", category: "Languages", difficulty: 2 },

  // Countries
  { word: "United States", category: "Countries", difficulty: 2 },
  { word: "Canada", category: "Countries", difficulty: 2 },
  { word: "Mexico", category: "Countries", difficulty: 2 },
  { word: "Brazil", category: "Countries", difficulty: 2 },
  { word: "Argentina", category: "Countries", difficulty: 2 },
  { word: "United Kingdom", category: "Countries", difficulty: 2 },
  { word: "France", category: "Countries", difficulty: 2 },
  { word: "Germany", category: "Countries", difficulty: 2 },
  { word: "Italy", category: "Countries", difficulty: 2 },
  { word: "Spain", category: "Countries", difficulty: 2 },
  { word: "China", category: "Countries", difficulty: 2 },
  { word: "Japan", category: "Countries", difficulty: 2 },
  { word: "South Korea", category: "Countries", difficulty: 2 },
  { word: "India", category: "Countries", difficulty: 2 },
  { word: "Pakistan", category: "Countries", difficulty: 2 },
  { word: "Bangladesh", category: "Countries", difficulty: 2 },
  { word: "Russia", category: "Countries", difficulty: 2 },
  { word: "Ukraine", category: "Countries", difficulty: 2 },
  { word: "Poland", category: "Countries", difficulty: 2 },
  { word: "Sweden", category: "Countries", difficulty: 2 },
  { word: "Norway", category: "Countries", difficulty: 2 },
  { word: "Denmark", category: "Countries", difficulty: 2 },
  { word: "Finland", category: "Countries", difficulty: 2 },
  { word: "Australia", category: "Countries", difficulty: 2 },
  { word: "New Zealand", category: "Countries", difficulty: 2 },
  { word: "South Africa", category: "Countries", difficulty: 2 },
  { word: "Egypt", category: "Countries", difficulty: 2 },
  { word: "Nigeria", category: "Countries", difficulty: 2 },
  { word: "Kenya", category: "Countries", difficulty: 2 },
  { word: "Ethiopia", category: "Countries", difficulty: 2 },
  { word: "Turkey", category: "Countries", difficulty: 2 },
  { word: "Saudi Arabia", category: "Countries", difficulty: 2 },
  { word: "Iran", category: "Countries", difficulty: 2 },
  { word: "Iraq", category: "Countries", difficulty: 2 },
  { word: "Afghanistan", category: "Countries", difficulty: 2 },
  { word: "Thailand", category: "Countries", difficulty: 2 },
  { word: "Vietnam", category: "Countries", difficulty: 2 },
  { word: "Malaysia", category: "Countries", difficulty: 2 },
  { word: "Indonesia", category: "Countries", difficulty: 2 },
  { word: "Philippines", category: "Countries", difficulty: 2 },
  { word: "Myanmar", category: "Countries", difficulty: 2 },
  { word: "Greece", category: "Countries", difficulty: 2 },
  { word: "Portugal", category: "Countries", difficulty: 2 },
  { word: "Switzerland", category: "Countries", difficulty: 2 },
  { word: "Austria", category: "Countries", difficulty: 2 },
  { word: "Netherlands", category: "Countries", difficulty: 2 },
  { word: "Belgium", category: "Countries", difficulty: 2 },
  { word: "Czech Republic", category: "Countries", difficulty: 2 },
  { word: "Hungary", category: "Countries", difficulty: 2 },

  // Bands
  { word: "The Beatles", category: "Bands", difficulty: 2 },
  { word: "The Rolling Stones", category: "Bands", difficulty: 2 },
  { word: "Led Zeppelin", category: "Bands", difficulty: 2 },
  { word: "Pink Floyd", category: "Bands", difficulty: 2 },
  { word: "Queen", category: "Bands", difficulty: 2 },
  { word: "Nirvana", category: "Bands", difficulty: 2 },
  { word: "Metallica", category: "Bands", difficulty: 2 },
  { word: "AC/DC", category: "Bands", difficulty: 2 },
  { word: "The Eagles", category: "Bands", difficulty: 2 },
  { word: "Red Hot Chili Peppers", category: "Bands", difficulty: 2 },
  { word: "The Who", category: "Bands", difficulty: 2 },
  { word: "Green Day", category: "Bands", difficulty: 2 },
  { word: "Foo Fighters", category: "Bands", difficulty: 2 },
  { word: "Blink-182", category: "Bands", difficulty: 2 },
  { word: "Pearl Jam", category: "Bands", difficulty: 2 },
  { word: "Radiohead", category: "Bands", difficulty: 2 },
  { word: "The Cure", category: "Bands", difficulty: 2 },
  { word: "The Clash", category: "Bands", difficulty: 2 },
  { word: "Oasis", category: "Bands", difficulty: 2 },
  { word: "The Smiths", category: "Bands", difficulty: 2 },
  { word: "R.E.M.", category: "Bands", difficulty: 2 },
  { word: "U2", category: "Bands", difficulty: 2 },
  { word: "The Doors", category: "Bands", difficulty: 2 },
  { word: "The Beach Boys", category: "Bands", difficulty: 2 },
  { word: "Guns N' Roses", category: "Bands", difficulty: 2 },
  { word: "Van Halen", category: "Bands", difficulty: 2 },
  { word: "Kiss", category: "Bands", difficulty: 2 },
  { word: "The Police", category: "Bands", difficulty: 2 },
  { word: "The Smashing Pumpkins", category: "Bands", difficulty: 2 },
  { word: "Paramore", category: "Bands", difficulty: 2 },
  { word: "Fall Out Boy", category: "Bands", difficulty: 2 },
  { word: "My Chemical Romance", category: "Bands", difficulty: 2 },
  { word: "Panic! at the Disco", category: "Bands", difficulty: 2 },
  { word: "The Strokes", category: "Bands", difficulty: 2 },
  { word: "Arctic Monkeys", category: "Bands", difficulty: 2 },
  { word: "Coldplay", category: "Bands", difficulty: 2 },
  { word: "Imagine Dragons", category: "Bands", difficulty: 2 },
  { word: "The Killers", category: "Bands", difficulty: 2 },
  { word: "Twenty One Pilots", category: "Bands", difficulty: 2 },

  // Food
  { word: "Pizza", category: "Food", difficulty: 2 },
  { word: "Burger", category: "Food", difficulty: 2 },
  { word: "Pasta", category: "Food", difficulty: 2 },
  { word: "Sushi", category: "Food", difficulty: 2 },
  { word: "Taco", category: "Food", difficulty: 2 },
  { word: "Steak", category: "Food", difficulty: 2 },
  { word: "Salad", category: "Food", difficulty: 2 },
  { word: "Soup", category: "Food", difficulty: 2 },
  { word: "Sandwich", category: "Food", difficulty: 2 },
  { word: "Fries", category: "Food", difficulty: 2 },
  { word: "Rice", category: "Food", difficulty: 2 },
  { word: "Noodles", category: "Food", difficulty: 2 },
  { word: "Dumplings", category: "Food", difficulty: 2 },
  { word: "Hot Dog", category: "Food", difficulty: 2 },
  { word: "Curry", category: "Food", difficulty: 2 },
  { word: "BBQ Ribs", category: "Food", difficulty: 2 },
  { word: "Fried Chicken", category: "Food", difficulty: 2 },
  { word: "Fish and Chips", category: "Food", difficulty: 2 },
  { word: "Mac and Cheese", category: "Food", difficulty: 2 },
  { word: "Lasagna", category: "Food", difficulty: 2 },
  { word: "Burrito", category: "Food", difficulty: 2 },
  { word: "Pancakes", category: "Food", difficulty: 2 },
  { word: "Waffles", category: "Food", difficulty: 2 },
  { word: "Omelette", category: "Food", difficulty: 2 },
  { word: "French Toast", category: "Food", difficulty: 2 },
  { word: "Bacon", category: "Food", difficulty: 2 },
  { word: "Sausage", category: "Food", difficulty: 2 },
  { word: "Eggs Benedict", category: "Food", difficulty: 2 },
  { word: "Chicken Wings", category: "Food", difficulty: 2 },
  { word: "Clam Chowder", category: "Food", difficulty: 2 },
  { word: "Pho", category: "Food", difficulty: 2 },
  { word: "Pad Thai", category: "Food", difficulty: 2 },
  { word: "Gyoza", category: "Food", difficulty: 2 },
  { word: "Spring Rolls", category: "Food", difficulty: 2 },
  { word: "Dim Sum", category: "Food", difficulty: 2 },
  { word: "Falafel", category: "Food", difficulty: 2 },
  { word: "Shawarma", category: "Food", difficulty: 2 },
  { word: "Hummus", category: "Food", difficulty: 2 },

  // Philosophers
  { word: "Socrates", category: "Philosophers", difficulty: 3 },
  { word: "Plato", category: "Philosophers", difficulty: 3 },
  { word: "Aristotle", category: "Philosophers", difficulty: 3 },
  { word: "Confucius", category: "Philosophers", difficulty: 3 },
  { word: "Laozi", category: "Philosophers", difficulty: 3 },
  { word: "Zhuangzi", category: "Philosophers", difficulty: 3 },
  { word: "Sun Tzu", category: "Philosophers", difficulty: 3 },
  { word: "Thomas Aquinas", category: "Philosophers", difficulty: 3 },
  { word: "René Descartes", category: "Philosophers", difficulty: 3 },
  { word: "John Locke", category: "Philosophers", difficulty: 3 },
  { word: "Immanuel Kant", category: "Philosophers", difficulty: 3 },
  { word: "Georg Hegel", category: "Philosophers", difficulty: 3 },
  { word: "Friedrich Nietzsche", category: "Philosophers", difficulty: 3 },
  { word: "Karl Marx", category: "Philosophers", difficulty: 3 },
  { word: "Jean-Paul Sartre", category: "Philosophers", difficulty: 3 },
  { word: "Simone de Beauvoir", category: "Philosophers", difficulty: 3 },
  { word: "David Hume", category: "Philosophers", difficulty: 3 },
  { word: "Baruch Spinoza", category: "Philosophers", difficulty: 3 },
  { word: "Michel Foucault", category: "Philosophers", difficulty: 3 },
  { word: "Albert Camus", category: "Philosophers", difficulty: 3 },
  { word: "John Stuart Mill", category: "Philosophers", difficulty: 3 },
  { word: "Thomas Hobbes", category: "Philosophers", difficulty: 3 },
  { word: "Jean-Jacques Rousseau", category: "Philosophers", difficulty: 3 },
  { word: "Bertrand Russell", category: "Philosophers", difficulty: 3 },
  { word: "Ludwig Wittgenstein", category: "Philosophers", difficulty: 3 },
  { word: "Slavoj Žižek", category: "Philosophers", difficulty: 3 },
  { word: "Hannah Arendt", category: "Philosophers", difficulty: 3 },
  { word: "Gilles Deleuze", category: "Philosophers", difficulty: 3 },
  { word: "Jacques Derrida", category: "Philosophers", difficulty: 3 },
  { word: "Edmund Husserl", category: "Philosophers", difficulty: 3 },
  { word: "Martin Heidegger", category: "Philosophers", difficulty: 3 },
  { word: "Augustine of Hippo", category: "Philosophers", difficulty: 3 },
  { word: "Francis Bacon", category: "Philosophers", difficulty: 3 },
  { word: "John Rawls", category: "Philosophers", difficulty: 3 },
  { word: "Alasdair MacIntyre", category: "Philosophers", difficulty: 3 },
  { word: "Noam Chomsky", category: "Philosophers", difficulty: 3 },
  { word: "Karl Popper", category: "Philosophers", difficulty: 3 },
  { word: "Richard Rorty", category: "Philosophers", difficulty: 3 },

  // Greek Mythology
  { word: "Zeus", category: "Greek Mythology", difficulty: 3 },
  { word: "Hera", category: "Greek Mythology", difficulty: 3 },
  { word: "Poseidon", category: "Greek Mythology", difficulty: 3 },
  { word: "Hades", category: "Greek Mythology", difficulty: 3 },
  { word: "Athena", category: "Greek Mythology", difficulty: 3 },
  { word: "Apollo", category: "Greek Mythology", difficulty: 3 },
  { word: "Artemis", category: "Greek Mythology", difficulty: 3 },
  { word: "Ares", category: "Greek Mythology", difficulty: 3 },
  { word: "Hermes", category: "Greek Mythology", difficulty: 3 },
  { word: "Dionysus", category: "Greek Mythology", difficulty: 3 },
  { word: "Aphrodite", category: "Greek Mythology", difficulty: 3 },
  { word: "Hephaestus", category: "Greek Mythology", difficulty: 3 },
  { word: "Demeter", category: "Greek Mythology", difficulty: 3 },
  { word: "Persephone", category: "Greek Mythology", difficulty: 3 },
  { word: "Cronus", category: "Greek Mythology", difficulty: 3 },
  { word: "Rhea", category: "Greek Mythology", difficulty: 3 },
  { word: "Uranus", category: "Greek Mythology", difficulty: 3 },
  { word: "Gaia", category: "Greek Mythology", difficulty: 3 },
  { word: "Nyx", category: "Greek Mythology", difficulty: 3 },
  { word: "Erebus", category: "Greek Mythology", difficulty: 3 },
  { word: "Eros", category: "Greek Mythology", difficulty: 3 },
  { word: "Thanatos", category: "Greek Mythology", difficulty: 3 },
  { word: "Hypnos", category: "Greek Mythology", difficulty: 3 },
  { word: "Nike", category: "Greek Mythology", difficulty: 3 },
  { word: "Nemesis", category: "Greek Mythology", difficulty: 3 },
  { word: "Typhon", category: "Greek Mythology", difficulty: 3 },
  { word: "Echidna", category: "Greek Mythology", difficulty: 3 },
  { word: "Medusa", category: "Greek Mythology", difficulty: 3 },
  { word: "Minotaur", category: "Greek Mythology", difficulty: 3 },
  { word: "Cerberus", category: "Greek Mythology", difficulty: 3 },
  { word: "Chimera", category: "Greek Mythology", difficulty: 3 },
  { word: "Sphinx", category: "Greek Mythology", difficulty: 3 },
  { word: "Pegasus", category: "Greek Mythology", difficulty: 3 },
  { word: "Hercules", category: "Greek Mythology", difficulty: 3 },
  { word: "Achilles", category: "Greek Mythology", difficulty: 3 },
  { word: "Odysseus", category: "Greek Mythology", difficulty: 3 },
  { word: "Jason", category: "Greek Mythology", difficulty: 3 },
  { word: "Theseus", category: "Greek Mythology", difficulty: 3 },

  // Medical Terms
  { word: "Cardiomyopathy", category: "Medical Terms", difficulty: 4 },
  { word: "Hypertension", category: "Medical Terms", difficulty: 4 },
  { word: "Arrhythmia", category: "Medical Terms", difficulty: 4 },
  { word: "Aneurysm", category: "Medical Terms", difficulty: 4 },
  { word: "Embolism", category: "Medical Terms", difficulty: 4 },
  { word: "Thrombosis", category: "Medical Terms", difficulty: 4 },
  { word: "Myocardial infarction", category: "Medical Terms", difficulty: 4 },
  { word: "Cerebrovascular accident", category: "Medical Terms", difficulty: 4 },
  { word: "Epistaxis", category: "Medical Terms", difficulty: 4 },
  { word: "Pneumothorax", category: "Medical Terms", difficulty: 4 },
  { word: "Bronchitis", category: "Medical Terms", difficulty: 4 },
  { word: "Asthma", category: "Medical Terms", difficulty: 4 },
  { word: "Emphysema", category: "Medical Terms", difficulty: 4 },
  { word: "Pulmonary fibrosis", category: "Medical Terms", difficulty: 4 },
  { word: "Gastroesophageal reflux", category: "Medical Terms", difficulty: 4 },
  { word: "Hepatitis", category: "Medical Terms", difficulty: 4 },
  { word: "Cirrhosis", category: "Medical Terms", difficulty: 4 },
  { word: "Pancreatitis", category: "Medical Terms", difficulty: 4 },
  { word: "Nephritis", category: "Medical Terms", difficulty: 4 },
  { word: "Renal failure", category: "Medical Terms", difficulty: 4 },
  { word: "Glomerulonephritis", category: "Medical Terms", difficulty: 4 },
  { word: "Osteoporosis", category: "Medical Terms", difficulty: 4 },
  { word: "Arthritis", category: "Medical Terms", difficulty: 4 },
  { word: "Rheumatoid arthritis", category: "Medical Terms", difficulty: 4 },
  { word: "Bursitis", category: "Medical Terms", difficulty: 4 },
  { word: "Tendonitis", category: "Medical Terms", difficulty: 4 },
  { word: "Sciatica", category: "Medical Terms", difficulty: 4 },
  { word: "Neuralgia", category: "Medical Terms", difficulty: 4 },
  { word: "Neuropathy", category: "Medical Terms", difficulty: 4 },
  { word: "Encephalitis", category: "Medical Terms", difficulty: 4 },
  { word: "Meningitis", category: "Medical Terms", difficulty: 4 },
  { word: "Sepsis", category: "Medical Terms", difficulty: 4 },
  { word: "Anemia", category: "Medical Terms", difficulty: 4 },
  { word: "Leukemia", category: "Medical Terms", difficulty: 4 },
  { word: "Lymphoma", category: "Medical Terms", difficulty: 4 },
  { word: "Melanoma", category: "Medical Terms", difficulty: 4 },
  { word: "Carcinoma", category: "Medical Terms", difficulty: 4 },
  { word: "Sarcoma", category: "Medical Terms", difficulty: 4 },

  // Writers
  { word: "William Shakespeare", category: "Writers", difficulty: 3 },
  { word: "Jane Austen", category: "Writers", difficulty: 3 },
  { word: "Charles Dickens", category: "Writers", difficulty: 3 },
  { word: "Mark Twain", category: "Writers", difficulty: 3 },
  { word: "Ernest Hemingway", category: "Writers", difficulty: 3 },
  { word: "F. Scott Fitzgerald", category: "Writers", difficulty: 3 },
  { word: "Leo Tolstoy", category: "Writers", difficulty: 3 },
  { word: "Fyodor Dostoevsky", category: "Writers", difficulty: 3 },
  { word: "Gabriel García Márquez", category: "Writers", difficulty: 3 },
  { word: "George Orwell", category: "Writers", difficulty: 3 },
  { word: "J.R.R. Tolkien", category: "Writers", difficulty: 3 },
  { word: "J.K. Rowling", category: "Writers", difficulty: 3 },
  { word: "Agatha Christie", category: "Writers", difficulty: 3 },
  { word: "Stephen King", category: "Writers", difficulty: 3 },
  { word: "Isaac Asimov", category: "Writers", difficulty: 3 },
  { word: "Ray Bradbury", category: "Writers", difficulty: 3 },
  { word: "H.G. Wells", category: "Writers", difficulty: 3 },
  { word: "Mary Shelley", category: "Writers", difficulty: 3 },
  { word: "Edgar Allan Poe", category: "Writers", difficulty: 3 },
  { word: "Emily Dickinson", category: "Writers", difficulty: 3 },
  { word: "Walt Whitman", category: "Writers", difficulty: 3 },
  { word: "Toni Morrison", category: "Writers", difficulty: 3 },
  { word: "James Baldwin", category: "Writers", difficulty: 3 },
  { word: "Harper Lee", category: "Writers", difficulty: 3 },
  { word: "Virginia Woolf", category: "Writers", difficulty: 3 },
  { word: "Sylvia Plath", category: "Writers", difficulty: 3 },
  { word: "Franz Kafka", category: "Writers", difficulty: 3 },
  { word: "Albert Camus", category: "Writers", difficulty: 3 },
  { word: "Jean-Paul Sartre", category: "Writers", difficulty: 3 },
  { word: "Homer", category: "Writers", difficulty: 3 },
  { word: "Dante Alighieri", category: "Writers", difficulty: 3 },
  { word: "Geoffrey Chaucer", category: "Writers", difficulty: 3 },
  { word: "Miguel de Cervantes", category: "Writers", difficulty: 3 },
  { word: "Herman Melville", category: "Writers", difficulty: 3 },
  { word: "Emily Brontë", category: "Writers", difficulty: 3 },
  { word: "Charlotte Brontë", category: "Writers", difficulty: 3 },
  { word: "Louisa May Alcott", category: "Writers", difficulty: 3 },
  { word: "Oscar Wilde", category: "Writers", difficulty: 3 },
  { word: "Aldous Huxley", category: "Writers", difficulty: 3 },

  // Automobile Companies
  { word: "Toyota", category: "Automobile Companies", difficulty: 3 },
  { word: "Honda", category: "Automobile Companies", difficulty: 3 },
  { word: "Ford", category: "Automobile Companies", difficulty: 3 },
  { word: "Chevrolet", category: "Automobile Companies", difficulty: 3 },
  { word: "Tesla", category: "Automobile Companies", difficulty: 3 },
  { word: "BMW", category: "Automobile Companies", difficulty: 3 },
  { word: "Mercedes-Benz", category: "Automobile Companies", difficulty: 3 },
  { word: "Audi", category: "Automobile Companies", difficulty: 3 },
  { word: "Volkswagen", category: "Automobile Companies", difficulty: 3 },
  { word: "Porsche", category: "Automobile Companies", difficulty: 3 },
  { word: "Lexus", category: "Automobile Companies", difficulty: 3 },
  { word: "Subaru", category: "Automobile Companies", difficulty: 3 },
  { word: "Mazda", category: "Automobile Companies", difficulty: 3 },
  { word: "Hyundai", category: "Automobile Companies", difficulty: 3 },
  { word: "Kia", category: "Automobile Companies", difficulty: 3 },
  { word: "Nissan", category: "Automobile Companies", difficulty: 3 },
  { word: "Infiniti", category: "Automobile Companies", difficulty: 3 },
  { word: "Acura", category: "Automobile Companies", difficulty: 3 },
  { word: "Mitsubishi", category: "Automobile Companies", difficulty: 3 },
  { word: "Jeep", category: "Automobile Companies", difficulty: 3 },
  { word: "Chrysler", category: "Automobile Companies", difficulty: 3 },
  { word: "Dodge", category: "Automobile Companies", difficulty: 3 },
  { word: "Ram", category: "Automobile Companies", difficulty: 3 },
  { word: "Buick", category: "Automobile Companies", difficulty: 3 },
  { word: "GMC", category: "Automobile Companies", difficulty: 3 },
  { word: "Cadillac", category: "Automobile Companies", difficulty: 3 },
  { word: "Lincoln", category: "Automobile Companies", difficulty: 3 },
  { word: "Fiat", category: "Automobile Companies", difficulty: 3 },
  { word: "Alfa Romeo", category: "Automobile Companies", difficulty: 3 },
  { word: "Maserati", category: "Automobile Companies", difficulty: 3 },
  { word: "Ferrari", category: "Automobile Companies", difficulty: 3 },
  { word: "Lamborghini", category: "Automobile Companies", difficulty: 3 },
  { word: "Bentley", category: "Automobile Companies", difficulty: 3 },
  { word: "Rolls-Royce", category: "Automobile Companies", difficulty: 3 },
  { word: "McLaren", category: "Automobile Companies", difficulty: 3 },
  { word: "Aston Martin", category: "Automobile Companies", difficulty: 3 },
  { word: "Lotus", category: "Automobile Companies", difficulty: 3 },
  { word: "Bugatti", category: "Automobile Companies", difficulty: 3 },

  // Motorcycle Companies
  { word: "Harley-Davidson", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Honda", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Yamaha", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Kawasaki", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Suzuki", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Ducati", category: "Motorcycle Companies", difficulty: 3 },
  { word: "BMW Motorrad", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Triumph", category: "Motorcycle Companies", difficulty: 3 },
  { word: "KTM", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Aprilia", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Moto Guzzi", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Indian Motorcycle", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Royal Enfield", category: "Motorcycle Companies", difficulty: 3 },
  { word: "MV Agusta", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Bajaj", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Hero MotoCorp", category: "Motorcycle Companies", difficulty: 3 },
  { word: "TVS Motor", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Benelli", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Husqvarna", category: "Motorcycle Companies", difficulty: 3 },
  { word: "GasGas", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Cagiva", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Bimota", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Norton", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Arch Motorcycle", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Lightning Motorcycle", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Zero Motorcycles", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Energica", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Vespa", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Piaggio", category: "Motorcycle Companies", difficulty: 3 },
  { word: "SYM", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Kymco", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Lifan", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Zongshen", category: "Motorcycle Companies", difficulty: 3 },
  { word: "CFMoto", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Loncin", category: "Motorcycle Companies", difficulty: 3 },
  { word: "UM Motorcycles", category: "Motorcycle Companies", difficulty: 3 },
  { word: "Surron", category: "Motorcycle Companies", difficulty: 3 },

  // Famous Singers
  { word: "Elvis Presley", category: "Famous Singers", difficulty: 3 },
  { word: "Michael Jackson", category: "Famous Singers", difficulty: 3 },
  { word: "Madonna", category: "Famous Singers", difficulty: 3 },
  { word: "Whitney Houston", category: "Famous Singers", difficulty: 3 },
  { word: "Freddie Mercury", category: "Famous Singers", difficulty: 3 },
  { word: "Aretha Franklin", category: "Famous Singers", difficulty: 3 },
  { word: "Beyoncé", category: "Famous Singers", difficulty: 3 },
  { word: "Adele", category: "Famous Singers", difficulty: 3 },
  { word: "Taylor Swift", category: "Famous Singers", difficulty: 3 },
  { word: "Frank Sinatra", category: "Famous Singers", difficulty: 3 },
  { word: "Billie Eilish", category: "Famous Singers", difficulty: 3 },
  { word: "Lady Gaga", category: "Famous Singers", difficulty: 3 },
  { word: "Ed Sheeran", category: "Famous Singers", difficulty: 3 },
  { word: "Bruno Mars", category: "Famous Singers", difficulty: 3 },
  { word: "Justin Bieber", category: "Famous Singers", difficulty: 3 },
  { word: "Shakira", category: "Famous Singers", difficulty: 3 },
  { word: "Dolly Parton", category: "Famous Singers", difficulty: 3 },
  { word: "Bob Dylan", category: "Famous Singers", difficulty: 3 },
  { word: "John Lennon", category: "Famous Singers", difficulty: 3 },
  { word: "Paul McCartney", category: "Famous Singers", difficulty: 3 },
  { word: "Elton John", category: "Famous Singers", difficulty: 3 },
  { word: "Prince", category: "Famous Singers", difficulty: 3 },
  { word: "David Bowie", category: "Famous Singers", difficulty: 3 },
  { word: "Stevie Wonder", category: "Famous Singers", difficulty: 3 },
  { word: "Janis Joplin", category: "Famous Singers", difficulty: 3 },
  { word: "Tina Turner", category: "Famous Singers", difficulty: 3 },
  { word: "Mariah Carey", category: "Famous Singers", difficulty: 3 },
  { word: "Christina Aguilera", category: "Famous Singers", difficulty: 3 },
  { word: "Ariana Grande", category: "Famous Singers", difficulty: 3 },
  { word: "Eminem", category: "Famous Singers", difficulty: 3 },
  { word: "Drake", category: "Famous Singers", difficulty: 3 },
  { word: "Rihanna", category: "Famous Singers", difficulty: 3 },
  { word: "Harry Styles", category: "Famous Singers", difficulty: 3 },
  { word: "Bobby Brown", category: "Famous Singers", difficulty: 3 },
  { word: "Sam Smith", category: "Famous Singers", difficulty: 3 },
  { word: "Lana Del Rey", category: "Famous Singers", difficulty: 3 },
  { word: "Miley Cyrus", category: "Famous Singers", difficulty: 3 },
  { word: "Selena Gomez", category: "Famous Singers", difficulty: 3 },

  // Continue with other categories...
].map(item => ({
  word: item.word.trim(),
  category: item.category.trim(),
  difficulty: item.difficulty
}));
